name: Assign Issue to Copilot

on:
  workflow_call:
    inputs:
      issue_number:
        description: "Issue number to assign to Copilot"
        required: true
        type: number

jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Assign issue to Copilot
        uses: otto-de/assign_issue_toCopilot_action@v1.0.1
        with:
          issue_number: ${{ inputs.issue_number }}
          github_token: ${{ secrets.COPILOT_PAT }}
